#pragma once
#ifdef VK_ENABLE_TESTS

FORCE_LINK_TEST(FreeAll, NoLeakAfterSimulatedLevelUnload)
FORCE_LINK_TEST(HW, DeviceHandlesNotNull)
FORCE_LINK_TEST(HW, DiscreteGPUSelected)
FORCE_LINK_TEST(HW, RequiredFeaturesPresent)
FORCE_LINK_TEST(HW, SyncObjectsAllocated)
FORCE_LINK_TEST(HW, CommandBufferCount)
FORCE_LINK_TEST(HW, DepthBufferFormat)
FORCE_LINK_TEST(Memory, DeviceLocalAllocFree)
FORCE_LINK_TEST(Memory, StagingBufferMapped)
FORCE_LINK_TEST(Memory, UploadBufferRoundTrip)
FORCE_LINK_TEST(Memory, DescriptorRingBufferMapped)
FORCE_LINK_TEST(PipelineCache, HashIsStable)
FORCE_LINK_TEST(PipelineCache, HashDiffersOnFormatChange)
FORCE_LINK_TEST(PipelineCache, NullModulesSkippedGracefully)
FORCE_LINK_TEST(PipelineLayout, EmptyBindingsStillValid)
FORCE_LINK_TEST(PipelineLayout, SingleUBOBinding)
FORCE_LINK_TEST(PipelineLayout, TwoSetLayout_UBOPlusSampler)
FORCE_LINK_TEST(PipelineLayout, SharedBindingMergesStages)
FORCE_LINK_TEST(Reflection, MinimalVertexShaderNoBindings)
FORCE_LINK_TEST(Reflection, MinimalFragmentShaderNoBindings)
FORCE_LINK_TEST(Reflection, MalformedInputReturnsSafe)
FORCE_LINK_TEST(Reflection, NullInputReturnsSafe)
FORCE_LINK_TEST(Reflection, SPIRVMagicWordAccepted)
FORCE_LINK_TEST(Reflection, NonSPIRVReturnsNull)
// FORCE_LINK_TEST(DynamicStreams, LockReturnsMappedPointer)
// FORCE_LINK_TEST(DynamicStreams, TwoLocksNoOverlap)
// FORCE_LINK_TEST(DynamicStreams, RingWrapSucceeds)
// FORCE_LINK_TEST(DynamicStreams, ZeroSizeLockSafe)
// FORCE_LINK_TEST(Texture, AllocAndUpload_4x4_RGBA8)
// FORCE_LINK_TEST(Texture, LargeAllocationGracefulDegradation)
// FORCE_LINK_TEST(Texture, SamplerHasValidFilter)
FORCE_LINK_TEST(VertexDecl, LevelDeclStride)
FORCE_LINK_TEST(VertexDecl, LevelDeclLength)
FORCE_LINK_TEST(VertexDecl, SkinnedDeclStride)
FORCE_LINK_TEST(VertexDecl, TwoStreamStrides)
FORCE_LINK_TEST(VertexDecl, NullDeclSafe)
FORCE_LINK_TEST(Layer5_MT, ThreadLocalContext_DefaultsToPrimary)
FORCE_LINK_TEST(Layer5_MT, PipelineCache_ConcurrentBindNoCorruption)
FORCE_LINK_TEST(Layer5_MT, DescriptorManager_ConcurrentAllocNoCorruption)
FORCE_LINK_TEST(Layer5_MT, PipelineCache_ConcurrentCompileNoCorruption)
FORCE_LINK_TEST(Layer5_MT, TTAPI_WakeLatencyBounded)
FORCE_LINK_TEST(Layer5_MT, ProgressiveLOD_WorkerNeverWritesCache)
FORCE_LINK_TEST(Layer5_MT, TreeWind_MainThreadOnlyUpdate)
FORCE_LINK_TEST(Layer5_MT, ConstantBuffer_PerWorkerStagingIsolation)
FORCE_LINK_TEST(Layer5_MT, WorkerXformSeed_ReResolvesAfterUnmap)

#endif // VK_ENABLE_TESTS
