#include "stdafx.h"
#ifdef VK_ENABLE_TESTS
#include "../vk_TestRunner.h"
#include "../../Resources/vk_ShaderReflection.h"
#include "../../Resources/vk_Shader.h"

// Embedded blobs generated by generate_spirv_headers.bat
#include "spirv_blobs/white_triangle_vert.h"  // white_triangle_vert_spv[], _len
#include "spirv_blobs/white_triangle_frag.h"  // white_triangle_frag_spv[], _len

// The minimal shaders above have NO uniform bindings — reflection should return empty.
VK_TEST(Reflection, MinimalVertexShaderNoBindings)
{
    auto bindings = vk_ShaderReflection::ReflectSPIRV(
        reinterpret_cast<const uint32_t*>(white_triangle_vert_spv),
        white_triangle_vert_spv_len);
    VK_EXPECT(bindings.empty());
    return true;
}

VK_TEST(Reflection, MinimalFragmentShaderNoBindings)
{
    auto bindings = vk_ShaderReflection::ReflectSPIRV(
        reinterpret_cast<const uint32_t*>(white_triangle_frag_spv),
        white_triangle_frag_spv_len);
    VK_EXPECT(bindings.empty());
    return true;
}

// Verify that ReflectSPIRV is safe against malformed input — should return empty, not crash.
VK_TEST(Reflection, MalformedInputReturnsSafe)
{
    uint32_t garbage[8] = {0xDEADBEEF, 1, 2, 3, 4, 5, 6, 7};
    auto bindings = vk_ShaderReflection::ReflectSPIRV(garbage, sizeof(garbage));
    VK_EXPECT(bindings.empty());
    return true;
}

// Null input must return empty without crashing (ASAN / null-deref guard).
VK_TEST(Reflection, NullInputReturnsSafe)
{
    auto bindings = vk_ShaderReflection::ReflectSPIRV(nullptr, 0);
    VK_EXPECT(bindings.empty());
    return true;
}

// Verify the SPIR-V magic word test: anything starting with 0x07230203 must NOT
// be rejected by the validator in vk_CreateShaderModule.
VK_TEST(Reflection, SPIRVMagicWordAccepted)
{
    // vk_CreateShaderModule checks magic before calling the API.
    // Use our embedded blob which is valid SPIR-V.
    VkShaderModule mod = vk_CreateShaderModule(
        HW.m_vkDevice,
        white_triangle_vert_spv,
        white_triangle_vert_spv_len);
    VK_EXPECT(mod != VK_NULL_HANDLE);
    vk_DestroyShaderModule(HW.m_vkDevice, mod);
    return true;
}

// Verify raw HLSL text (non-SPIR-V) returns VK_NULL_HANDLE — not an API crash.
VK_TEST(Reflection, NonSPIRVReturnsNull)
{
    const char hlsl[] = "float4 main() : SV_Target { return float4(1,0,0,1); }";
    VkShaderModule mod = vk_CreateShaderModule(
        HW.m_vkDevice, hlsl, sizeof(hlsl));
    VK_EXPECT(mod == VK_NULL_HANDLE);
    return true;
}

#endif // VK_ENABLE_TESTS
